version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - '3000:3000'
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      POSTGRES_DB: db
      REDIS_HOST: redis
      REDIS_PORT: 6379
      JWT_SECRET: secret_key
      LLM_API_KEY: AIzaSyD5E3fccV_kccW4ZHBAckmgKmpcKVuDSHQ
    command: npm run start:dev
    restart: unless-stopped

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      POSTGRES_DB: db
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - '6379:6379'
    restart: unless-stopped

volumes:
  pgdata: